# =========================================================
# PROFIL DEVELOPPEMENT
# =========================================================

# ---------------------------------------------------------
# Database - H2 en mémoire
# ---------------------------------------------------------
spring.datasource.url=jdbc:h2:mem:devdb
spring.h2.console.enabled=true

# ---------------------------------------------------------
# JPA / Hibernate
# ---------------------------------------------------------
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# ---------------------------------------------------------
# Logging
# ---------------------------------------------------------
logging.level.root=INFO
logging.level.fr.univjardinage.jardinage=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ---------------------------------------------------------
# Configuration métier - Développement
# ---------------------------------------------------------
app.stock.auto-reorder=true
app.pricing.max-discount-rate=50.0