# =========================================================
# PROFIL PRODUCTION
# =========================================================

# ---------------------------------------------------------
# Database - PostgreSQL
# ---------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/jardinagedb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ---------------------------------------------------------
# JPA / Hibernate
# ---------------------------------------------------------
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

# ---------------------------------------------------------
# Logging
# ---------------------------------------------------------
logging.level.root=WARN
logging.level.fr.univjardinage.jardinage=INFO

# ---------------------------------------------------------
# Configuration métier - Production
# ---------------------------------------------------------
app.stock.auto-reorder=true
app.pricing.max-discount-rate=20.0

# ---------------------------------------------------------
# Sécurité
# ---------------------------------------------------------
server.ssl.enabled=true