# Application
spring.application.name=gestion -produits -jardinage

# Logging
logging.level.root=INFO
logging.level.fr.univjardinage.jardinage=DEBUG
logging.pattern.console =%d{yyyy -MM-dd HH:mm:ss} - %msg%n

# H2 Database
spring.datasource.url=jdbc:h2:mem:jardinagedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database -platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl -auto=create -drop
spring.jpa.show -sql=true

# Demo data
app.demo.data.enabled=true